### PR TITLE
Update for PR 4248

### PR DESCRIPTION
**Pull request by lexming**
I updated your PR https://github.com/easybuilders/easybuild-framework/pull/4248 with the following changes to the reproducible archives:
* use reproducible archive for git repos without `.git.` dir
* set timestamps with `touch`
* avoid deprecated `GZIP` environment variable by piping into `gzip`

This PR looks messy because I'm also syncing to current state of `5.0.x` branch.
The meaningful commit is https://github.com/Rovanion/easybuild-framework/commit/8d9e14eb6d72490c675adb8a70415a4c735cc0bc

### CODE REVIEW

**Comment by Rovanion** [comment]
I left some minor comments on https://github.com/Rovanion/easybuild-framework/commit/8d9e14eb6d72490c675adb8a70415a4c735cc0bc but other than that, without having actually run the code, it looks good to me.

**Comment by lexming** [comment]
@Rovanion I replied to your comments. If you are happy with the changes please merge it and we can continue in the PR for easybuild.

**Comment by Rovanion** [comment]
If you are OK with a merge commit I can merge it in, though the history will probably become quite ugly. A rebase of mine and your commits ontop of whatever branch you want to merge it to is more effort of course, but will result in a cleaner history.

**Comment by lexming** [comment]
Merge commits are allowed in EasyBuild, no problem. We use them all the time.

**Pull request merged**
